[package]
name = "learning"
version = "0.1.0"
edition = "2024"

[dependencies]
clust = "0.9.0"
rand = "0.9.0"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
